### ISSUE TITLE
Error when use scatter_mul on cuda

### ISSUE THREAD

**Issue by ha0ransun** [rusty1s/pytorch_scatter#204]
I install the torch_scatter 2.0.6 and I meet this error when I use scatter_mul on cuda. Here is my test script:

```
import torch
from torch_scatter import scatter
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)
print(torch.arange(4, device=device))
src = torch.tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]]).to(device)
index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]]).to(device)
scatter(src, index, reduce='sum')
print(torch.arange(4, device=device))
scatter(src, index, reduce='mul')
print(torch.arange(4, device=device))
```
Here is the output:
```
cuda:0
tensor([0, 1, 2, 3], device='cuda:0')
tensor([0, 1, 2, 3], device='cuda:0')
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    print(torch.arange(4, device=device))
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)
```
scatter_sum works well. while this problem also exists for scatter_max and scatter_min.

**Comment by rusty1s** [comment]
Works for me. How did you try to install `torch_scatter`? Do you make use of our wheels? Were there any error messages during installation?

**Comment by ha0ransun** [comment]
I create a new environment with py3.8, Cuda 11.1 and install pytorch_scatter using your wheels. The problem is fixed. 

I did not use your wheels. I could not find the error message during installation. I guess the problem is I did not install it correctly.
