### ISSUE TITLE
Simply importing torch_scatter causes CUDA error with PyTorch 1.9 and cuda 11.1

### ISSUE THREAD

**Issue by krishnap25** [rusty1s/pytorch_scatter#225]
Hello, 

Here is the minimal working example of my error:
```
import torch
z = torch.zeros(10, device=torch.device('cuda:0'))  # works
import torch_scatter
z = torch.zeros(10, device=torch.device('cuda:0'))  # Error
# RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
z = torch.zeros(5, device=torch.device('cpu')) # works
```

Here are my installation and system details:
- OS: Ubuntu 20.04.1 LTS
- GPU: Quadro GP100
- torch version: 1.9.0
- torch_scatter version: 2.0.7
- CUDA version (as given by `torch.version.cuda`): 11.1

Other details:
- I installed PyTorch via conda. The installation works fine and I can train models as per usual.
- The same error persists for torch_scatter installed via conda or via the pip command ` pip install  torch-scatter -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html`

Any pointers on how to fix this will be appreciated. Thanks!

**Comment by rusty1s** [comment]
Can you give me some information about your GPU driver version? It might be necessary to upgrade it according to [this thread](https://forums.developer.nvidia.com/t/provided-ptx-was-compiled-with-an-unsupported-toolchain-error-using-cub/168292).

**Comment by krishnap25** [comment]
The GPU driver version is 450.80.02, which is compatible with CUDA 11.1. 

Do you know of any other workarounds apart from updating the drivers? Would an older version of torch_scatter work with this driver version?

**Comment by rusty1s** [comment]
I think one option which would help me to identify the error is to try to install `torch-scatter` from source. If the installation succeeds, then there might be some issues in how we build our wheels. For this, simply clone `pytorch_scatter` and run `python setup.py install`.

**Comment by yuhaozhang** [comment]
I am running into exactly the same issue. Running the code by @krishnap25 above is giving the same output and error. I tried installing `pytorch_scatter` from source by cloning the GitHub repo, and the error did **not** go away.

- OS: Ubuntu 18.04.5 LTS
- GPU: NVIDIA  A100-SXM4-40GB
- GPU driver: 450.119.03
- torch version: 1.9.0
- torch_scatter version: 2.0.7
- CUDA version (as given by torch.version.cuda): 11.1

**Comment by rusty1s** [comment]
Thanks for letting me know. Can you try to run via:
```
export TORCH_CUDA_ARCH_LIST="3.5;5.0+PTX;6.0;7.0;7.5;8.0;8.6"
rm -rf build/ && python setup.py install

**Comment by yuhaozhang** [comment]
Tried as instructed, but the same error was triggered when a tensor was being copied to CUDA:
```
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Running with `CUDA_LAUNCH_BLOCKING=1` does not give any additional information.

**Comment by krishnap25** [comment]
Same as @yuhaozhang, I still have the error after compiling from source on master with TORCH_CUDA_ARCH_LIST as you suggested.

**Comment by rusty1s** [comment]
I'm not really sure how to fix that. There are a tons of result on Google and they all suggest to update the driver or downgrading CUDA :(

**Comment by yuhaozhang** [comment]
Thanks. I will give downgrading CUDA a try soon and see if it fixes the issue. Will keep this updated.

**Comment by yuhaozhang** [comment]
Downgrading CUDA from 11.1 to 11.0 and installing `pytorch-scatter` from source has solved the issue for me. I can now copy tensors to CUDA without the previous CUDA error.

**Comment by RomeoV** [comment]
This still seems to be an issue - I have the same issue with `pytorch==1.9.0` and `cuda==11.1`.
Downgrading isn't really an option here either, due to the way our computing nodes are set up.
If there is any more news, that would be greatly appreciated.

**Comment by rusty1s** [comment]
Thanks for reaching out, still not sure how to fix that on my end. Any pointers appreciated.

**Comment by RomeoV** [comment]
I have figured out the problem, and a possible solution (thanks to @ntselepidis for helping me out). The problem lies in a compatibility issue with newer Nvidia GPU architectures -- in fact the default `setup.py` and `CMakeLists.txt` demands compute_capabilty `3.5`, which is quite old and not compatible with newer architectures. Note also that the `nvcc` compiler warns you that `arch=sm_35` will soon not be supported anymore.
> $nvcc --help  # version 11.1
> --gpu-architecture <arch>           (-arch)
> Note: the values compute_30, compute_32, compute_35, compute_37, sm_30, sm_32, sm_35, sm_37 and sm_50 are deprecated and may be removed a future release.

In my case, I was trying to run the code on a `GTX 1080 Ti` (Pascal architecture, compute capability 6.1) and `V100` (Volta architecture, compute capability 7.0).

## Solving the problem just for your machine
If you are just interested in getting the code to run on your specific machine, it is sufficient to clone the github repository and remove the `-sm_35` flags from the [`setup.py`](https://github.com/rusty1s/pytorch_scatter/blob/9d4cf96d3f11de0b911f78b57914da9d303d3dd7/setup.py#L51) and [`CMakeLists.txt`](https://github.com/rusty1s/pytorch_scatter/blob/9d4cf96d3f11de0b911f78b57914da9d303d3dd7/CMakeLists.txt#L12). **Note that you have to do this both for `pytorch_scatter` and `pytorch_sparse`.** Then, when running `python setup.py install` for each of them, cuda will automatically detect your graphics card and compile for that architecture.

## Compiling for different architectures
As far as I understand, the nvidia compiler `nvcc` is able to compile directly for certain architectures, as well as generate a `virtual` code (called PTX) that is able to be used for forwards-compatibility.

For example, the [Nvidia Ampere compatibility guide](https://docs.nvidia.com/cuda/ampere-compatibility-guide/index.html) suggests compiling like this:
```
/usr/local/cuda/bin/nvcc
  -gencode=arch=compute_52,code=sm_52
  -gencode=arch=compute_60,code=sm_60
  -gencode=arch=compute_61,code=sm_61
  -gencode=arch=compute_70,code=sm_70
  -gencode=arch=compute_75,code=sm_75
  -gencode=arch=compute_80,code=sm_80
  -gencode=arch=compute_80,code=compute_80
  -O2 -o mykernel.o -c mykernel.cu
```
These flags could be added to `setup.py`. This would generate explicit code for compute capabilities `5.2, 6.0, ..., 8.0` aswell as PTX code (forwards compatibility) from 8.0.


@rusty1s wrote
> Thanks for letting me know. Can you try to run via:
> 
> ```
> export TORCH_CUDA_ARCH_LIST="3.5;5.0+PTX;6.0;7.0;7.5;8.0;8.6"
> rm -rf build/ && python setup.py install
> ```

This is the same idea, and is parsed by the [`./cmake/public/utils.cmake`](https://github.com/pytorch/pytorch/blob/d1cbee7b2b1da94ff1a0fa880bd0173de27fb89f/cmake/public/utils.cmake#L370) file in the official pytorch code. But I believe this is not parsed in this repository, so setting it will have no effect.

## Possible PR
- Remove `-sm_35` from `setup.py` and `CMakeLists.txt` both for `pytorch_sparse` and `pytorch_scatter`
- When building binaries for pypy, compile with the flags listed above to support all (?) gpu architectures (possibly even add some older architectures to the compile flags).
- (optional) include support for `TORCH_CUDA_ARCH_LIST` by using the `utils.cmake` script mentioned above.

@rusty1s Let me know if you have any thoughts on this - I am happy to set up a pull request that incorporates these ideas.

**Comment by rusty1s** [comment]
Sounds great. Thanks for digging into this. Please feel free to set up a PR so we can quickly fix this.

**Comment by yuhaozhang** [comment]
Thanks for the fix! @RomeoV @rusty1s 

I can confirm that manual build and installation from the latest of `master` branch is now working with my PyTorch 1.9.0 installation and A100 GPU card. Yay!

However, installation from the pre-built binaries via anaconda or pypi is still throwing the same errors. I think the pre-built binaries were not updated with this fix yet. Can we expect update to the anaconda or pypi installations soon that fixes this issue?

**Comment by rusty1s** [comment]
Yes, will probably release new versions early September.

**Comment by rusty1s** [comment]
Wheels have been updated :)

**Comment by yuhaozhang** [comment]
Thanks @rusty1s. I was going to ask about the timeline for the new release, but since the wheels are now up to date, the current latest already fixed this issue.

**Comment by marcioluish** [comment]
Hi @yuhaozhang I'm trying to use scatter on a A100 nvidia gpu too but I'm having trouble.
Have you used docker? If so, do you have a its dockerfile on github?

**Comment by RomeoV** [comment]
@marcioluish I used it in the docker image `romeov/ml4co-gpu` and I recall it working for me on modern gpus

**Comment by marcioluish** [comment]
> @marcioluish I used it in the docker image `romeov/ml4co-gpu` and I recall it working for me on modern gpus

hi @RomeoV! Do you have link to this image?

**Comment by RomeoV** [comment]
You can just run `docker pull romeov/ml4co-gpu`
