### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device for scatter_max

### ISSUE THREAD

**Issue by ytzhao** [rusty1s/pytorch_scatter#274]
Hi all,

I meet a CUDA Runtime error when calling `scatter_max`, this is how it happens:

```
import torch
from torch_scatter import scatter_max

src = torch.tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]])
index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]])

out, argmax = scatter_max(src, index, dim=-1)
```
(1) if `src` and `index` are on cpu, everything is fine
(2) but, when i move `src` and `index` to gpu, the CUDA Runtime error occurs

<img width="683" alt="image" src="https://user-images.githubusercontent.com/12531708/156802699-f041167a-d8ea-4118-8792-d45ffab7a8d2.png">

my dev environment：
- inside a docker container, torch-scatter is pre-installed by pip via docker build, `pip3 install torch-scatter`
- pytorch verson: 1.10.0 + cuda113 (torch.cuda.is_available() = True)
- torch_scatter version: 2.0.9 (torch_scatter.cuda_version = 11030, but it still doesn't support scatter_max on GPU)

P.S:
I solved the problem by reinstalling torch-scatter inside docker
`pip3 install --force-reinstall torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html`
the torch-scatter version and cuda_version does NOT change after reinstalling!

but, i'm really confused what has happened, why should i reinstall this package? is there any solution that i don't need to re-install this package inside a docker.

**Comment by rusty1s** [comment]
I'm actually not sure. Might be related to the issue mentioned [here](https://github.com/rusty1s/pytorch_scatter#from-source).

**Comment by ytzhao** [comment]
> I'm actually not sure. Might be related to the issue mentioned [here](https://github.com/rusty1s/pytorch_scatter#from-source).

Hi @rusty1s, thank you for your reply. I've double checked all the settings mentioned in the README.md, everything is good. 

FYI, i use python3.6.9.

But, I checked the md5 of (1) `pip install torch-scatter` and (2) `pip3 install torch-scatter https://data.pyg.org/whl/torch-1.10.0+cu113.html`, the whl can be found on page: https://data.pyg.org/whl/torch-1.10.0+cu113.html. 

both md5 and SHA256 are different between (1) and (2), is this reasonable?

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/12531708/156865285-ed7980c2-4486-4b10-9241-aac88cc64a9b.png">
<img width="721" alt="image" src="https://user-images.githubusercontent.com/12531708/156865407-21f95d62-9a2e-4725-99ef-d1dd0940d796.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/12531708/156865444-d7bb08bf-348e-409a-96c2-4ebae05acfaa.png">

**Comment by rusty1s** [comment]
Yes, that is to be expected. Note that `pip install torch-scatter` only downloads the source files and compiles them, while `pip install torch-scatter -f torch-scatter https://data.pyg.org/whl/torch-1.10.0+cu113.html` downloads pre-compiled data than can be directly used.

**Comment by ytzhao** [comment]
> Yes, that is to be expected. Note that `pip install torch-scatter` only downloads the source files and compiles them, while `pip install torch-scatter -f torch-scatter https://data.pyg.org/whl/torch-1.10.0+cu113.html` downloads pre-compiled data than can be directly used.

thanks for your explanation in details, i tried to `pip install torch-scatter -f torch-scatter https://data.pyg.org/whl/torch-1.10.0+cu113.html` in a docker, the CUDA ops can be called correctly.

**Comment by zjhthu** [comment]
Hi, I also encounted this problem. I built the docker on a 2080TI GPU and everything was fine. But when I tested the pre-built docker on a P100 GPU, I met`RuntimeError: CUDA error: no kernel image is available for execution on the device`.
Pytorch version is 1.11.0a0+bfe5ad2, CUDA version is 11.6. 
I reinstall pytorch-scatter by `RUN FORCE_CUDA=1 pip3 install --no-cache-dir --verbose --force-reinstall torch-scatter -f https://data.pyg.org/whl/torch-1.11.0+116.html`, but it did not work.

**Comment by ytzhao** [comment]
@zjhthu Hi Jiahui
(1) according to this ci cuda page: https://github.com/rusty1s/pytorch_scatter/tree/62a958f467bf80c3f566083b4949ec21e2be57d0/.github/workflows/cuda, i didn't find the proper version compatible with cuda 11.6
(2) and from this page: https://data.pyg.org/whl/, there's NO whl for torch-1.11.0

**Comment by zjhthu** [comment]
@ytzhao ，I resolved this problem by building from the source code. `TORCH_CUDA_ARCH_LIST` should be set in the Dockerfile.
 ```
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.2+PTX 7.5+PTX"
RUN FORCE_CUDA=1 pip3 install --no-cache-dir --verbose ./
```

**Comment by ytzhao** [comment]
> @ytzhao ，I resolved this problem by building from the source code. `TORCH_CUDA_ARCH_LIST` should be set in the Dockerfile.
> 
> ```
> ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.2+PTX 7.5+PTX"
> RUN FORCE_CUDA=1 pip3 install --no-cache-dir --verbose ./
> ```

Great! 👏👏
