### ISSUE TITLE
Scatter max cause RuntimeError for tensors with gradient

### ISSUE THREAD

**Issue by Vimos** [rusty1s/pytorch_scatter#37]
I am using `scatter_max` to get max logits for each of the indexed group, when I comment out the last line the code runs well. 

```
            logits = model(batch)
            for i, (l, r) in enumerate(windowed(accumulate([0] + batch.graph.batch_num_nodes, operator.add), 2)):
                x = logits[l:r].squeeze()
                y = batch.graph.ndata['y'][l:r]
                idx = batch.graph.ndata['cid'][l:r]
                yy, _ = scatter_max(y, idx)
                # xx, _ = scatter_max(x, idx.to(device))
```
Howerver, if the code is excuted, I will get some `RuntimeError: CUDA error: an illegal memory access was encountered`.

Notice that `logits` is a cuda tensor, `idx` is a cpu tensor, I am not sure if this is the reason.

The only difference between `y` and `x` is, `x` contains a gradient part while `y` is a pure tensor.

A sample of `idx` is like below
```
tensor([   1,   11,    4,   19,   19,   19,   19,    6,   19,   11,   12,   19,
          19,   24, -100, -100,   22,   19,   19,   27,   14,   19,   19,   27,
          19,    6,   11,   14,   19,   16,   25,   15,   31,   10,    9,   31,
           1,   27,   14,   19,   21,   30,   19,   32,   19,   19,    7,   24,
          23,    5,    8,    2,   19,    4,   19,    1,   22,   18,   19,   19,
           4,   29,    0,   28,   19,   17,   19,    4,   25,   17,   19,   26,
          21,   11,   11,   12,    1,    1,    4,   19,   19,   19,   19,   19,
          19,   19,   13,    3,    4,   19,   32,   30,   19,   21,   20, -100,
        -100, -100, -100])
```

Any hints over this problem? Thanks!

**Comment by rusty1s** [comment]
Hi, `idx` needs to be a CUDA tensor and its values need to be greater than or equal to 0.

**Comment by Vimos** [comment]
Thanks for the quick reply and it works after fixing the negative `idx`!

So in my case, `idx` works for 
```
yy, _ = scatter_max(y, idx)
``` 
but not 
```
yy, _ = scatter_max(y, idx)
xx, _ = scatter_max(x, idx.to(device))
``` 
This may due to negatives break the cuda memory when computing `yy`, even though that is not reported.
