### ISSUE TITLE
Pytorch 2.0.0 & Cuda 11.4 on aarch64

### ISSUE THREAD

**Issue by YoushaaMurhij** [rusty1s/pytorch_scatter#384]
Hi,
I am trying to build torch-scatter on aarch64 with cuda11.4  and pytorch 2.0 using this command:
```bash
RUN pip3 install torch-scatter==2.1.1 -f https://data.pyg.org/whl/torch-2.0.0+cu114.html
```
But I got this error message while running the application:
```
RuntimeError: Not compiled with CUDA support
```
Could you please guide me how to build it correctly?
Thanks

**Comment by rusty1s** [comment]
There does not exist a https://data.pyg.org/whl/torch-2.0.0+cu114.html version. Try https://data.pyg.org/whl/torch-2.0.0+cu113.html

**Comment by YoushaaMurhij** [comment]
I am trying to build pytorch scatter on jetson xavier. It has cuda 11.4. I do not think it is an option for me to upgrade cuda.
does building from main branch with force cuda flag work?

**Comment by rusty1s** [comment]
Yes, you can also try `FORCE_CUDA=1 pip install torch-scatter`.

**Comment by YoushaaMurhij** [comment]
Yes, it works for me on aarch with cuda11.4. 
Thanks for your response!
