### ISSUE TITLE
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by r3dir3ct** [rusty1s/pytorch_scatter#86]
`torch_scatter`: 1.2.0
`torch.version.cuda`: 10.0.130
`CUDA_HOME`:/usr/local/cuda-10.0
Similar issue as [this](https://github.com/rusty1s/pytorch_geometric/issues/114#issuecomment-477403628). The `/usr/local/cuda` on the server points to the `/usr/local/cuda-8.0`, but I do not have the `root` privilege to change the symbol link. So, any workaround? Does it really always find the path of `/usr/local/cuda` instead of the `CUDA_HOME`?

**Comment by r3dir3ct** [comment]
I found that the reason is that I set the `CUDA_HOME` after the installation.
So now I fixed it by reinstalling/rebuilding.
